### ISSUE TITLE
Tab-to-indent does not respect indentation settings

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#32]
I'm in an environment where the tab size is set to 3 (via an `.editorconfig` file, but not sure if that matters). When pressing <kbd>Tab</kbd> to indent a line within a template, it always indents by 4 spaces. Interestingly, when pressing <kbd>Shift-Tab</kbd> to de-indent, it removes **3** spaces. The correct behaviour would be that <kbd>Tab</kbd> indents by 3 spaces as well.

![recording](https://user-images.githubusercontent.com/4145923/93017309-d5a6d900-f5c7-11ea-97f8-400b39283f39.gif)

**Comment by bjansen** [comment]
Are you guys the same person or what? https://github.com/bjansen/pebble-intellij/issues/48 😄

Thanks for reporting the problem, I should be able to fix it the same way.

**Comment by bjansen** [comment]
Huh, another one that seems to be already fixed in `master`, please try the build I mentioned in https://github.com/antlr/jetbrains-plugin-st4/issues/31#issuecomment-691957518

**Comment by bjansen** [comment]
Actually it's not entirely fixed. If you configure a template data language (for example if you are generating a Java file), then it does not use Java indents. It always uses "Other File Types" indents, which seems to be wrong.

Otherwise, when no template data language is configured, "Other File Types" indents will always be used in `.st` and `.stg` files.

**Comment by Clashsoft** [comment]
Can confirm that the problem is still there with language injection in the latest snapshot (https://github.com/antlr/jetbrains-plugin-st4/issues/31#issuecomment-691957518)
